20220101
20220101

diff --git a/trunk/build_firmware_modify b/trunk/build_firmware_modify
--- a/trunk/build_firmware_modify
+++ b/trunk/build_firmware_modify
@@ -1,11 +1,13 @@
 #!/bin/bash
 
 if [ -z "$1" ] || [ "$EUID" != 0 ]; then
-	echo "Please run 'fakeroot $0 PRODUCT_NAME' to start build (see 'configs/templates/') " && exit 1
+	echo "Please run 'fakeroot $0 PRODUCT_NAME' to start build (see 'configs/templates/')"
+	echo "For Windows Subsystem for Linux(WSL), use 'fakeroot-tcp' instead of 'fakeroot', or run with sudo"
+	exit 1
 fi
-if [ -z "$2" ];then
+
 if [ ! -f configs/templates/$1.config ] ; then
-	echo "configs/templates/$1.config not found "
+	echo "configs/templates/$1.config not found!"
 	exit 1
 fi
 
@@ -188,7 +190,7 @@ rm -rf "$dir_wifi_dst/mt7615"
 mkdir -p "$dir_wifi_dst/mt76x3"
 cp -f "$dir_wifi_src/rtpci/4.1.X.X/mt76x3/Kconfig" "$dir_wifi_dst/mt76x3/Kconfig"
 mkdir -p "$dir_wifi_dst/mt7615/embedded"
-cp -f "$dir_wifi_src/rtpci/4.4.2.1/mt7615/embedded/Kconfig" "$dir_wifi_dst/mt7615/embedded/Kconfig"
+cp -f "$dir_wifi_src/rtpci/5.0.5.1/mt7615/embedded/Kconfig" "$dir_wifi_dst/mt7615/embedded/Kconfig"
 
 if [ -n "$CONFIG_RT2860V2_AP" ] ; then
 	dir_wifi_ver="2.7.X.X"
@@ -262,17 +264,17 @@ if [ -n "$CONFIG_MT7628_AP" ] ; then
 fi
 if [ -n "$CONFIG_MT7615_AP" ] ; then
 	dir_wifi_ver="4.4.2.1"
-	if [ "$CONFIG_FIRMWARE_WIFI_DRIVER" = "5.0.3.0" ] || \
-		[ "$CONFIG_FIRMWARE_WIFI2_DRIVER" = "5.0.3.0" ] || \
-		[ "$CONFIG_FIRMWARE_WIFI5_DRIVER" = "5.0.3.0" ]; then
-		dir_wifi_ver="5.0.3.0"
-	elif [ "$CONFIG_FIRMWARE_WIFI_DRIVER" = "5.0.4.0" ] || \
+	if [ "$CONFIG_FIRMWARE_WIFI_DRIVER" = "5.0.4.0" ] || \
 		[ "$CONFIG_FIRMWARE_WIFI2_DRIVER" = "5.0.4.0" ] || \
 		[ "$CONFIG_FIRMWARE_WIFI5_DRIVER" = "5.0.4.0" ]; then
+		dir_wifi_ver="5.0.3.0"
+	elif [ "$CONFIG_FIRMWARE_WIFI_DRIVER" = "5.0.5.1" ] || \
+		[ "$CONFIG_FIRMWARE_WIFI2_DRIVER" = "5.0.5.1" ] || \
+		[ "$CONFIG_FIRMWARE_WIFI5_DRIVER" = "5.0.5.1" ]; then
 		dir_wifi_ver="5.0.4.0"
 	fi
-	if [ "$CONFIG_FIRMWARE_WIFI_DRIVER" = "5.0.4.0" ] || [ "$CONFIG_FIRMWARE_WIFI2_DRIVER" = "5.0.4.0" ] || [ "$CONFIG_FIRMWARE_WIFI5_DRIVER" = "5.0.4.0" ]; then
-		dir_wifi_ver="5.0.4.0"
+	if [ "$CONFIG_FIRMWARE_WIFI_DRIVER" = "5.0.5.1" ] || [ "$CONFIG_FIRMWARE_WIFI2_DRIVER" = "5.0.5.1" ] || [ "$CONFIG_FIRMWARE_WIFI5_DRIVER" = "5.0.5.1" ]; then
+		dir_wifi_ver="5.0.5.1"
 	fi
 	cp -rfL "$dir_wifi_src/rtpci/$dir_wifi_ver/mt7615" "$dir_wifi_dst/"
 	cp -rfL "$dir_wifi_src/rtpci/$dir_wifi_ver/mt7615_ap" "$dir_wifi_dst/"
@@ -343,8 +345,12 @@ fi
 #SFE
 if [ "$CONFIG_FIRMWARE_INCLUDE_SFE" = "y" ] ; then
 	func_enable_kernel_param "CONFIG_SHORTCUT_FE"
+	func_enable_kernel_param "CONFIG_NF_CONNTRACK_EVENTS"
+	func_enable_kernel_param "CONFIG_NF_CONNTRACK_CHAIN_EVENTS"
 else
 	func_disable_kernel_param "CONFIG_SHORTCUT_FE"
+	func_disable_kernel_param "CONFIG_NF_CONNTRACK_EVENTS"
+	func_disable_kernel_param "CONFIG_NF_CONNTRACK_CHAIN_EVENTS"
 fi
 ############################# USB #####################################
 if [ "$CONFIG_FIRMWARE_ENABLE_USB" != "y" ] || [ -z "$CONFIG_USB_SUPPORT" ] ; then
